stages:
  - install
  - build
  - deploy

# Use the official Node.js image with the version you need for Astro.js
image: wci-git.llnl.gov:4567/lwds/node:18-chrome

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci # Clean install dependencies
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build # Run Astro's build command
  artifacts:
    paths:
      - dist/ # Ensure the built files are saved as artifacts

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y rsync ssh
    - echo "Deploying to production server"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > /tmp/ssh_private_key
    - chmod 600 /tmp/ssh_private_key
    - ssh-add /tmp/ssh_private_key
    - ssh-keyscan -H $VM_IPADDRESS >> ~/.ssh/known_hosts
    - rsync -avz --delete dist/ $SSH_USER@$VM_IPADDRESS:/var/www/html/ # Replace with your actual deployment path
  environment:
    name: production
    url: https://nif-dashboard.llnl.gov/ # Replace with your production URL

