stages:
  - install
  - build
  - deploy

# Use the official Node.js image with the version you need for Astro.js
image: wci-repo.llnl.gov:4567/lwds/node:18

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci # Clean install dependencies
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build # Run Astro's build command
  artifacts:
    paths:
      - dist/ # Ensure the built files are saved as artifacts

deploy:
  stage: deploy
  script:
  - cp -r dist/* /var/www/vhosts/
  - chmod -R 755 /var/www/vhosts/
  - chgrp -R apache /var/www/vhosts/
  environment:
    name: production
    url: https://nif-dashboard.llnl.gov/
  needs:
    - build
  tags:
    - production
