stages:
  - install
  - build
  - deploy

# Use the official Node.js image with the version you need for Astro.js
image: wci-git.llnl.gov:4567/lwds/node:18-chrome

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci # Clean install dependencies
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build # Run Astro's build command
  artifacts:
    paths:
      - public/ # Ensure the built files are saved as artifacts

deploy:
  stage: deploy
  script:
  - mkdir -p ~/.ssh
  - sudo ssh-keygen -R $VM_IPADDRESS
  - sudo ssh-keyscan -H $VM_IPADDRESS >> ~/.ssh/known_hosts
  - scp -r public/* $SSH_USER@$VM_IPADDRESS:/var/www/html
  environment:
    name: production
    url: https://nif-dashboard.llnl.gov/ # Replace with your production URL
  needs:
    - build
  tags:
    - production
