image: "node:18"

stages:
  - build
  - deploy

variables:
  GIT_SSL_NO_VERIFY: "1"  # Disables SSL verification for git commands

npm_install:
  stage: build
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - npm install -g npm@latest
    - npm cache clean --force
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > /tmp/ssh_private_key
    - chmod 600 /tmp/ssh_private_key
    - ssh-add /tmp/ssh_private_key
    # - ssh-add -l  # List all added identities for debugging
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # - cat ~/.ssh/known_hosts
    # - echo "Testing SSH authentication"
    # - ssh -vvv $SSH_USER@$VM_IPADDRESS "echo 'SSH authentication successful'"
  script:
    - npm install
    - ssh $SSH_USER@$VM_IPADDRESS "hostname && echo 'Welcome!!!' > welcome.txt"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

pages:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > /tmp/ssh_private_key
    - chmod 600 /tmp/ssh_private_key
    - ssh-add /tmp/ssh_private_key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp package.json $SSH_USER@$VM_IPADDRESS:/tmp/package.json
  script:
    - ssh $SSH_USER@$VM_IPADDRESS "cd /var/www/html && cp /tmp/package.json . && npm install -g npm@latest && npm cache clean --force && npm install || (cat /root/.npm/_logs/*.log && false)"
    - ssh $SSH_USER@$VM_IPADDRESS "cd /var/www/html && npm run build"
  artifacts:
    paths:
      - public
  only:
    - main