stages:
  - install
  - build
  - deploy

# Use the official Node.js image with the version you need for Astro.js
image: wci-git.llnl.gov:4567/lwds/node:18-chrome

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci # Clean install dependencies
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build # Run Astro's build command
  artifacts:
    paths:
      - dist/ # Ensure the built files are saved as artifacts

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
    - rsync -avz --delete dist/ $SSH_USER@$VM_IPADDRESS:/path/to/deployment/ # Replace with your actual deployment path
  environment:
    name: production
    url: http://your-production-url.com # Replace with your production URL
  only:
    - main # Run this job only on the main branch
