stages:
  - install
  - build
  - deploy

# Use the official Node.js image with the version you need for Astro.js
image: 

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci # Clean install dependencies
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build # Run Astro's build command
  artifacts:
    paths:
      - public/ # Ensure the built files are saved as artifacts

deploy:
  stage: deploy
  script:
  - cp -r public/* /var/www/html
  environment:
    name: production
    url:  # Replace with your production URL
  needs:
    - build
  tags:
    - production
