runtime: python39

handlers:
- url: /robots\.txt
  static_files: robots.txt
  mime_type: text/plain
  upload: robots\.txt

- url: /sitemap\.xml
  static_files: sitemap.xml
  mime_type: text/xml
  upload: sitemap\.xml

- url: /(.+)
  static_files: \1
  upload: dist/(.+)
  expiration: "15m"

- url: /
  static_files: index.html
  upload: dist/index.html
  secure: always

- url: /images/(.*)
  static_files: images/\1
  upload: dist/images/(.*)
  secure: always

- url: /(.*\.js)$
  static_files: \1
  upload: dist/.*/.*\.js$

- url: /_astro/(.*)  # Serve files from the _astro directory
  static_files: dist/_astro/\1
  upload: dist/_astro/(.*)
  secure: always