runtime: python35
api_version: 1
threadsafe: true

handlers:
- url: /robots\.txt
  static_files: robots.txt
  mime_type: text/plain
  upload: robots\.txt

- url: /sitemap\.xml
  static_files: sitemap.xml
  mime_type: text/xml
  upload: sitemap\.xml

- url: /(.+)
  static_files: \1
  upload: (.+)
  expiration: "15m"

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)
  secure: always

- url: /(.*\.js)$
  static_files: \1
  upload: .*/.*\.js$
